[package]
edition = "2021"
name = "multirate"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[profile.release]
debug = true

[dependencies]
multiversion = "0.6"
num-traits = "0.2"
